### ISSUE TITLE
Bug in refract?

### ISSUE THREAD

**Issue by xalanq** [MashPlant/ray_tracer#2]
`src/material.rs` line 19
`const R0: f32 = (NA - NG) * (NA - NG) / (NA + NG) * (NA + NG);`
should be
`const R0: f32 = (NA - NG) * (NA - NG) / ((NA + NG) * (NA + NG));`
?

**Comment by MashPlant** [comment]
You are right, thank you...
I will fix it when I have some leisure time for CG...
